name: build-and-test
on:
  workflow_dispatch:    
  push:
    branches: 
      - main
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'LICENSE'
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '5.0.x' ]
    name: Dotnet ${{ matrix.dotnet }} build
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Clean
        run: dotnet clean -c Debug

      - name: Build
        run: dotnet build -c Debug

      - name: Test
        run: dotnet test -c Debug --no-build -l trx --verbosity=normal
        
      - name: Calculate code coverage
        run: |
          dotnet new tool-manifest --force
          dotnet tool install coverlet.console
          dotnet coverlet ./tests/ForeverFactory.Tests/bin/Debug/net5.0/ForeverFactory.Tests.dll --target "dotnet" --targetargs "test ./tests/ForeverFactory.Tests --no-build" --format=opencover --use-source-link --output=opencover_coverage.xml

      - name: Publish code coverage as artifacts
        uses: actions/upload-artifact@v1
        with:
          name: CodeCoverageReport
          path: ./opencover_coverage.xml
          
      - name: Upload code coverage to Codecov
        run: |
          dotnet tool install codecov
          dotnet codecov -f "opencover_coverage.xml" -t ${{ secrets.CODECOV_TOKEN }}
