name: build-and-test
on:
  workflow_dispatch:    
  push:
    branches: 
      - main
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'LICENSE'
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '5.0.x' ]
    name: Dotnet ${{ matrix.dotnet }} build
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Clean
        run: dotnet clean -c Release

      - name: Build
        run: dotnet build -c Release

      - name: Test
        run: dotnet test -c Release --no-build -l trx --verbosity=normal